### ISSUE TITLE
Serial Commands

### ISSUE THREAD

**Issue by credenda** [reeltwo/AstroPixelsPlus#1]
Connecting on pin 16 directly on the ESP32 or via AstroPixels breakout board does not accept serial commands either from Marcduino via slave Teeces  serial pin, or via serial pins on generic Arduino with simple sketch connecting at baud rate of 9600. Before recent update when sending commands for RLD I would get ch: 50 ch: 54 ch: 13 or on serial monitor on the ESP32 but now this does not happen and I can no longer replicate.

Testing has only been on the RLD, web interface works fine on most options. Please Help!

**Comment by ethax-ross** [comment]
If you pull the latest version of ReelTwo and AstropixelsPlus it will work; this was just fixed yesterday (see https://github.com/reeltwo/AstroPixelsPlus/commit/589f6e2a694ef01deeef84024a862daadaf264f9). Here's a wiring diagram by Mowee:

![Compact-MarcDuino-Astropixles](https://user-images.githubusercontent.com/29867726/194742876-e98ebef6-ac02-4965-8f8d-f512b8731bb9.jpg)

**Comment by ethax-ross** [comment]
I almost forgot; you also need to change the baud rate to 2900 in the web UI; this matches the teeces and is what the Marcduino uses.

**Comment by credenda** [comment]
Thanks yes I noticed the update on the AstroPixels sketch infact it happened while I was working on this and I did update once I saw it. and I was already using the connections as you have illustrated, but no luck. However your second post is something I overlooked not sure if connected I went into the web interface and set the baud rate 2900 and we are in business! Thanks for your help.

**Comment by SkyJetty** [comment]
> 

Actually it needs to be a baud rate of 2400 to match teeces.
