### ISSUE TITLE
Error when sending *HPS303

### ISSUE THREAD

**Issue by davbow123** [reeltwo/AstroPixelsPlus#2]
22:42:36.627 -> Guru Meditation Error: Core  0 panic'ed (IntegerDivideByZero). Exception was unhandled.
22:42:36.627 -> 
22:42:36.627 -> Core  0 register dump:
22:42:36.627 -> PC      : 0x400dbb7f  PS      : 0x00060330  A0      : 0x800dbe1c  A1      : 0x3ffdc180  
22:42:36.627 -> A2      : 0x000000ff  A3      : 0x00000000  A4      : 0x00000009  A5      : 0x0000004b  
22:42:36.660 -> A6      : 0xffffffda  A7      : 0x3ffd9ba0  A8      : 0x800edef2  A9      : 0x3ffdc160  
22:42:36.660 -> A10     : 0x000400c2  A11     : 0x00000000  A12     : 0x000000c2  A13     : 0x000023c0  
22:42:36.660 -> A14     : 0x00000005  A15     : 0x00000001  SAR     : 0x0000000a  EXCCAUSE: 0x00000006  
22:42:36.660 -> EXCVADDR: 0x00000000  LBEG    : 0x40084e29  LEND    : 0x40084e31  LCOUNT  : 0x00000027  
22:42:36.692 -> 
22:42:36.692 -> 
22:42:36.692 -> Backtrace:0x400dbb7c:0x3ffdc1800x400dbe19:0x3ffdc1a0 0x400dbfae:0x3ffdc1c0 0x400d7639:0x3ffdc1e0 0x400e692b:0x3ffdc200 0x400e69f8:0x3ffdc220

**Comment by rimim** [comment]
Fixed in the latest version of the Reeltwo library.

**Comment by rimim** [comment]
Tested and confirmed to work in latest Reeltwo.
