### ISSUE TITLE
No hardware SPI pins defined

### ISSUE THREAD

**Issue by davbow123** [reeltwo/AstroPixelsPlus#3]
When I compile most recent version, get the following message;

In file included from c:\Users\davbo\Documents\Arduino\libraries\FastLED\src/FastLED.h:67,
                 from c:\Users\davbo\Documents\Arduino\libraries\Reeltwo_new\src/core/LEDPixelEngine.h:14,
                 from c:\Users\davbo\Documents\Arduino\libraries\Reeltwo_new\src/dome/LogicEngine.h:5,
                 from c:\Users\davbo\Documents\Arduino\libraries\Reeltwo_new\src/dome/Logics.h:5,
                 from C:\Users\davbo\Documents\Arduino\AstroPixelsPlus\AstroPixelsPlus.ino:98:
c:\Users\davbo\Documents\Arduino\libraries\FastLED\src/fastspi.h:145:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

Well aware some of these issues could be my ignorance . . . .

**Comment by rimim** [comment]
You can ignore the message. It is just a warning/reminder. We don't SPI for the LogicEngine.
